# Generated by Django 6.0.2 on 2026-02-26 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEarthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text="Original event id (CSV 'id' column)", max_length=100, unique=True)),
                ('time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=255)),
                ('magnitude', models.FloatField(db_column='mag', help_text="Magnitude (maps to CSV 'mag')", validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(10.0)])),
                ('mag_type', models.CharField(blank=True, choices=[('ml', 'ML'), ('mb', 'Mb'), ('ms', 'Ms'), ('mw', 'Mw'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('depth', models.FloatField(blank=True, help_text='Depth in kilometers', null=True)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('nst', models.IntegerField(blank=True, null=True)),
                ('gap', models.FloatField(blank=True, null=True)),
                ('dmin', models.FloatField(blank=True, null=True)),
                ('rms', models.FloatField(blank=True, null=True)),
                ('net', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('quake_type', models.CharField(blank=True, db_column='type', max_length=50, null=True)),
                ('horizontal_error', models.FloatField(blank=True, null=True)),
                ('depth_error', models.FloatField(blank=True, null=True)),
                ('mag_error', models.FloatField(blank=True, null=True)),
                ('mag_nst', models.IntegerField(blank=True, db_column='magNst', null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('location_source', models.CharField(blank=True, max_length=50, null=True)),
                ('mag_source', models.CharField(blank=True, max_length=50, null=True)),
                ('raw', models.JSONField(blank=True, help_text='Raw row JSON for provenance / debugging', null=True)),
            ],
            options={
                'verbose_name': 'Historical Earthquake',
                'verbose_name_plural': 'Historical Earthquakes',
                'ordering': ('-time',),
                'indexes': [models.Index(fields=['time'], name='earthquake__time_698c66_idx'), models.Index(fields=['magnitude'], name='earthquake__mag_889a29_idx'), models.Index(fields=['event_id'], name='earthquake__event_i_012fe1_idx'), models.Index(fields=['depth'], name='earthquake__depth_497c6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Total beds / capacity', null=True)),
                ('critical_beds', models.PositiveIntegerField(blank=True, help_text='ICU / critical care beds', null=True)),
                ('building_type', models.CharField(choices=[('reinforced_concrete', 'Reinforced concrete'), ('masonry', 'Masonry'), ('steel', 'Steel'), ('wood', 'Wood'), ('other', 'Other')], default='other', max_length=30)),
                ('floors', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('retrofit', models.BooleanField(default=False, help_text='Whether seismic retrofit has been applied')),
                ('primary_material', models.CharField(blank=True, help_text='Primary construction material', max_length=120)),
                ('owner_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('ngo', 'NGO / Non-profit')], default='public', max_length=20)),
                ('vulnerability_score', models.FloatField(blank=True, help_text='0 (low) - higher is more vulnerable', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.TextField(blank=True)),
                ('last_assessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'indexes': [models.Index(fields=['name'], name='earthquake__name_aa2775_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Model name, e.g. 'mag_predictor'", max_length=200)),
                ('version', models.CharField(default='v1', max_length=50)),
                ('file', models.FileField(blank=True, help_text='Trained model artifact (.pkl)', null=True, upload_to='models/')),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, help_text='Performance metrics (RMSE, R2, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-trained_at', '-created_at'),
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='HazardAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_risk', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, help_text='Features fed to the model at prediction time', null=True)),
                ('notes', models.TextField(blank=True)),
                ('earthquake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='earthquake.historicalearthquake')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='earthquake.hospital')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='earthquake.mlmodelversion')),
            ],
            options={
                'ordering': ('-assessed_at',),
            },
        ),
    ]
